import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { PrescriptionDocument } from './PrescriptionDocument';
import type { PrescriptionResponse } from '../../types/patientRecord';

function makePrescription(overrides: Partial<PrescriptionResponse> = {}): PrescriptionResponse {
  return {
    id: 'rx1',
    patient_record_id: 'rec1',
    prescribed_by: 7,
    prescribed_at: '2026-07-27T10:30:00Z',
    notes: 'Take with food. Report any swelling.',
    created_at: '2026-07-27T10:30:00Z',
    updated_at: '2026-07-27T10:30:00Z',
    items: [
      {
        id: 'it1',
        prescription_id: 'rx1',
        medicine_name: 'Amoxicillin',
        dosage: '500mg',
        frequency: 'TDS',
        duration: '5 days',
        instructions: 'After meals',
        created_at: '2026-07-27T10:30:00Z',
        updated_at: '2026-07-27T10:30:00Z',
      },
      {
        id: 'it2',
        prescription_id: 'rx1',
        medicine_name: 'Ibuprofen',
        dosage: '400mg',
        frequency: 'SOS',
        duration: '3 days',
        instructions: 'For pain',
        created_at: '2026-07-27T10:30:00Z',
        updated_at: '2026-07-27T10:30:00Z',
      },
    ],
    ...overrides,
  };
}

describe('PrescriptionDocument', () => {
  const basePatientProps = {
    patientName: 'Marcus Delaney',
    patientCode: 'PAT-000001',
    patientAge: 34,
    patientGender: 'male',
    patientDOB: '1992-06-14',
    prescriberName: 'Dr. Priya Raman',
  };

  it('renders patient, prescriber, date and medicines', () => {
    render(
      <PrescriptionDocument
        prescription={makePrescription()}
        {...basePatientProps}
      />,
    );

    expect(screen.getByText('Prescription')).toBeInTheDocument();
    // Date renders from the source record's prescribed_at (Jul 2026) —
    // once, in the metadata row (no duplicated app footer).
    expect(screen.getByText(/Jul/i)).toBeInTheDocument();
    // Application metadata never reaches the document.
    expect(screen.queryByText('Generated by DensCare')).not.toBeInTheDocument();
    expect(screen.queryByText('Dental clinic management')).not.toBeInTheDocument();
    expect(screen.getByText('Dr. Priya Raman')).toBeInTheDocument();
    expect(screen.getByText('Marcus Delaney')).toBeInTheDocument();
    expect(screen.getByText('PAT-000001')).toBeInTheDocument();
    expect(screen.getByText(/Age 34/i)).toBeInTheDocument();
    expect(screen.getByText(/DOB/i)).toBeInTheDocument();
    // Medicines with dosage / frequency / duration / instructions.
    expect(screen.getByText('Amoxicillin')).toBeInTheDocument();
    expect(screen.getByText('500mg')).toBeInTheDocument();
    expect(screen.getByText('TDS')).toBeInTheDocument();
    expect(screen.getByText('5 days')).toBeInTheDocument();
    expect(screen.getByText('After meals')).toBeInTheDocument();
    expect(screen.getByText('Ibuprofen')).toBeInTheDocument();
    expect(screen.getByText('For pain')).toBeInTheDocument();
    // Prescription-level notes.
    expect(screen.getByText('Take with food. Report any swelling.')).toBeInTheDocument();
  });

  it('falls back to placeholders when patient data is unresolved', () => {
    render(
      <PrescriptionDocument
        prescription={makePrescription()}
        patientName={null}
        patientCode={null}
        patientAge={null}
        patientGender={null}
        patientDOB={null}
        prescriberName={null}
      />,
    );

    expect(screen.getByText(/Patient #/)).toBeInTheDocument();
    // "User #7" fallback from the backend prescribed_by id.
    expect(screen.getByText('User #7')).toBeInTheDocument();
  });

  it('handles a long prescription with many medicines', () => {
    const items = Array.from({ length: 40 }, (_, i) => ({
      id: `med-${i}`,
      prescription_id: 'rx1',
      medicine_name: `Medicine ${i + 1}`,
      dosage: '100mg',
      frequency: 'BD',
      duration: '7 days',
      instructions: i % 2 === 1 ? `Long instruction text for medicine ${i + 1}` : null,
      created_at: '2026-07-27T10:30:00Z',
      updated_at: '2026-07-27T10:30:00Z',
    }));

    render(
      <PrescriptionDocument
        prescription={makePrescription({ items })}
        {...basePatientProps}
      />,
    );

    expect(screen.getByText('Medicine 1')).toBeInTheDocument();
    expect(screen.getByText('Medicine 40')).toBeInTheDocument();
    expect(screen.getAllByText('100mg').length).toBe(40);
    expect(screen.getByText('Long instruction text for medicine 2')).toBeInTheDocument();
    // Medicines without instructions render a dash.
    expect(screen.getAllByText('—').length).toBe(20);
  });
});
