import type { FC } from 'react';
import { Pill } from 'lucide-react';
import { Icon } from '../common/Icon/Icon';
import { formatISODate } from '../../utils/date';
import type { PrescriptionResponse } from '../../types/patientRecord';

interface PrescriptionDocumentProps {
  prescription: PrescriptionResponse;
  /** Resolved patient display name (null → fallback placeholder). */
  patientName: string | null;
  patientCode: string | null;
  patientAge: number | null;
  patientGender: string | null;
  patientDOB: string | null;
  /** Resolved prescriber display name — "User #id" fallback supplied by caller. */
  prescriberName: string | null;
}

/**
 * PrescriptionDocument — professional A4 printable prescription (Task 4).
 *
 * Pure presentational component fed by backend data:
 * - Prescription content (medicines, dosage, frequency, duration,
 *   instructions, notes) comes from GET /prescriptions/{id}.
 * - Patient name/code/age/DOB come from GET /patients/{id} (best-effort —
 *   the same patient query already powers the record page's name header).
 * - Prescriber name is resolved from the user directory (established
 *   `usePatientRecordNames` pattern) with a "User #id" fallback — the
 *   prescription API exposes `prescribed_by` as a user id only, and no
 *   doctor profile link exists on prescriptions (documented limitation —
 *   never fabricated).
 *
 * Minimum-necessary-data: phone, email and address are deliberately NOT
 * printed — the backend contract does not require them on the document.
 *
 * No application metadata leaks into the document: no "generated by"
 * stamp and no app tagline (the header carries only the system name
 * "DensCare" — clinic branding is not configured anywhere in the product).
 */
export const PrescriptionDocument: FC<PrescriptionDocumentProps> = ({
  prescription,
  patientName,
  patientCode,
  patientAge,
  patientGender,
  patientDOB,
  prescriberName,
}) => {
  const items = prescription.items;

  const patientDetailParts = [
    patientAge != null ? `Age ${patientAge}` : null,
    patientGender ? patientGender[0].toUpperCase() + patientGender.slice(1) : null,
    patientDOB ? `DOB ${formatISODate(patientDOB)}` : null,
  ].filter(Boolean);

  return (
    <div className="bg-white p-6 text-neutral-900" data-testid="prescription-document">
      {/* ── Header ─────────────────────────────────────────────── */}
      <div className="flex items-start justify-between gap-4 border-b-2 border-neutral-800 pb-4">
        <div>
          <p className="text-h3 font-bold uppercase tracking-wide text-neutral-900">DensCare</p>
        </div>
        <div className="flex items-center gap-2 text-right">
          <Icon icon={Pill} size="md" className="text-primary-500" />
          <div>
            <p className="text-h2 font-bold uppercase tracking-[0.2em] text-neutral-900">
              Prescription
            </p>
            <p className="mt-0.5 text-caption font-medium uppercase tracking-wide text-neutral-500">
              Rx
            </p>
          </div>
        </div>
      </div>

      {/* ── Metadata / parties ─────────────────────────────────── */}
      <div className="mt-4 grid grid-cols-2 gap-x-6 gap-y-2 text-body-sm">
        <div className="flex justify-between gap-3 border-b border-neutral-100 pb-1.5">
          <dt className="text-neutral-500">Date</dt>
          <dd className="font-semibold tabular-nums">
            {formatISODate(prescription.prescribed_at)}
          </dd>
        </div>
        <div className="flex justify-between gap-3 border-b border-neutral-100 pb-1.5">
          <dt className="text-neutral-500">Prescribed by</dt>
          <dd className="max-w-[60%] truncate font-semibold" title={prescriberName ?? undefined}>
            {prescriberName ?? `User #${prescription.prescribed_by}`}
          </dd>
        </div>
      </div>

      <div className="print-break-avoid mt-4 rounded-md bg-neutral-50 p-3">
        <p className="text-caption font-semibold uppercase tracking-wide text-neutral-500">
          Patient
        </p>
        <p className="mt-1 text-body font-semibold text-neutral-900">
          {patientName ?? `Patient #${prescription.patient_record_id.slice(0, 8)}`}
        </p>
        <div className="mt-0.5 flex flex-wrap gap-x-4 gap-y-0.5 text-body-sm text-neutral-500">
          {patientCode && <span className="tabular-nums">{patientCode}</span>}
          {patientDetailParts.length > 0 && (
            <span>{patientDetailParts.join(' · ')}</span>
          )}
        </div>
      </div>

      {/* ── Medicines ───────────────────────────────────────────── */}
      <table className="mt-5 w-full border-collapse text-left text-body-sm">
        <thead>
          <tr className="border-b-2 border-neutral-300 text-caption font-semibold uppercase tracking-wide text-neutral-500">
            <th scope="col" className="py-2 pr-3">#</th>
            <th scope="col" className="py-2 pr-3">Medicine</th>
            <th scope="col" className="py-2 pr-3">Dosage</th>
            <th scope="col" className="py-2 pr-3">Frequency</th>
            <th scope="col" className="py-2 pr-3">Duration</th>
            <th scope="col" className="py-2">Instructions</th>
          </tr>
        </thead>
        <tbody>
          {items.map((item, index) => (
            <tr key={item.id} className="align-top border-b border-neutral-100">
              <td className="py-2 pr-3 text-neutral-400 tabular-nums">{index + 1}</td>
              <td className="py-2 pr-3 font-medium text-neutral-900">
                {item.medicine_name}
              </td>
              <td className="py-2 pr-3 tabular-nums">{item.dosage}</td>
              <td className="py-2 pr-3 tabular-nums">{item.frequency}</td>
              <td className="py-2 pr-3 tabular-nums">{item.duration}</td>
              <td className="py-2 whitespace-pre-wrap break-words text-neutral-700">
                {item.instructions || '—'}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* ── Notes ──────────────────────────────────────────────── */}
      {prescription.notes && (
        <div className="print-break-avoid mt-4 rounded-md bg-neutral-50 p-3">
          <p className="text-caption font-semibold uppercase tracking-wide text-neutral-500">
            Notes
          </p>
          <p className="mt-1 whitespace-pre-wrap break-words text-body-sm text-neutral-700">
            {prescription.notes}
          </p>
        </div>
      )}

    </div>
  );
};
