import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/react';
import { InvoiceDocument } from './InvoiceDocument';
import type { InvoiceRead } from '../../../types/billing';

function makeInvoice(overrides: Partial<InvoiceRead> = {}): InvoiceRead {
  return {
    id: 'inv1',
    invoice_number: 'INV-01042',
    document_type: 'invoice',
    status: 'partially_paid',
    patient: {
      id: 'p1',
      patient_code: 'PAT-000001',
      full_name: 'Marcus Delaney',
      is_active: true,
    },
    doctor: {
      id: 'd1',
      doctor_code: 'DOC-000001',
      user_full_name: 'Dr. Priya Raman',
      is_active: true,
    },
    treatment_plan: null,
    appointment: null,
    creator: null,
    updater: null,
    invoice_date: '2026-07-23',
    due_date: '2026-08-22',
    currency_code: 'INR',
    notes: 'Follow up in two weeks',
    cancellation_reason: null,
    void_reason: null,
    items: [
      {
        id: 'i1',
        sequence_number: 1,
        description: 'Composite restoration — tooth 26',
        quantity: 2,
        unit_price: '320.00',
        discount_type: 'PERCENTAGE',
        discount_value: '32.00',
        net_amount: '288.00',
        tax_amount: null,
        currency_code: 'INR',
      },
    ],
    financials: {
      currency_code: 'INR',
      subtotal: '640.00',
      discount_total: '32.00',
      tax_total: '0.00',
      grand_total: '608.00',
      paid_amount: '320.00',
      outstanding_amount: '288.00',
    },
    version: 1,
    doc_version: 1,
    created_at: '2026-07-23T08:00:00Z',
    updated_at: '2026-07-23T08:00:00Z',
    created_by: 1,
    updated_by: null,
    ...overrides,
  };
}

describe('InvoiceDocument', () => {
  it('renders invoice metadata, patient, doctor, items and notes', () => {
    render(<InvoiceDocument invoice={makeInvoice()} />);

    expect(screen.getByText('Invoice')).toBeInTheDocument();
    // Invoice number appears once, in the metadata row (no app footer).
    expect(screen.getAllByText('INV-01042').length).toBe(1);
    // Payment status appears once, in the metadata row (not the header).
    expect(screen.getByText('Partially Paid')).toBeInTheDocument();
    expect(screen.getAllByText('Partially Paid').length).toBe(1);
    // Invoice date and due date appear once each (no duplicated footer).
    expect(screen.getByText(/Jul/i)).toBeInTheDocument();
    expect(screen.getByText(/Aug/i)).toBeInTheDocument();
    expect(screen.getByText('Marcus Delaney')).toBeInTheDocument();
    expect(screen.getByText('PAT-000001')).toBeInTheDocument();
    expect(screen.getByText('Dr. Priya Raman')).toBeInTheDocument();
    // Internal identifiers and application metadata never reach the document.
    expect(screen.queryByText('DOC-000001')).not.toBeInTheDocument();
    expect(screen.queryByText('Generated by DensCare')).not.toBeInTheDocument();
    expect(screen.queryByText('Dental clinic management')).not.toBeInTheDocument();
    expect(screen.getByText('Composite restoration — tooth 26')).toBeInTheDocument();
    expect(screen.getByText('Follow up in two weeks')).toBeInTheDocument();
  });

  it('renders correct financial values with INR formatting', () => {
    render(<InvoiceDocument invoice={makeInvoice()} />);

    // Line items: unit price, discount, net amount.
    expect(screen.getAllByText('₹32.00').length).toBe(2); // line discount + discount total
    expect(screen.getAllByText('₹320.00').length).toBe(2); // unit price + amount paid
    expect(screen.getAllByText('₹288.00').length).toBe(2); // line net + balance due
    // Summary: subtotal, discount total, grand total, paid, outstanding.
    expect(screen.getByText('₹640.00')).toBeInTheDocument();
    expect(screen.getByText('₹608.00')).toBeInTheDocument();
    expect(screen.getByText('Balance due')).toBeInTheDocument();
    expect(screen.getByText('Amount paid')).toBeInTheDocument();
    expect(screen.queryByText('Tax total')).not.toBeInTheDocument(); // tax is 0.00 (Phase 2)
  });

  it('shows the tax row only when the backend supplies tax', () => {
    render(
      <InvoiceDocument
        invoice={makeInvoice({
          items: [
            {
              id: 'i1',
              sequence_number: 1,
              description: 'Root canal',
              quantity: 1,
              unit_price: '1500.00',
              discount_type: null,
              discount_value: null,
              net_amount: '1500.00',
              tax_amount: '90.00',
              currency_code: 'INR',
            },
          ],
          financials: {
            currency_code: 'INR',
            subtotal: '1500.00',
            discount_total: '0.00',
            tax_total: '90.00',
            grand_total: '1590.00',
            paid_amount: '0.00',
            outstanding_amount: '1590.00',
          },
        })}
      />,
    );

    expect(screen.getByText('Tax total')).toBeInTheDocument();
    expect(screen.getByText('₹90.00')).toBeInTheDocument();
    // Grand total and balance due both render as ₹1,590.00 (nothing paid).
    expect(screen.getAllByText('₹1,590.00').length).toBe(2);
  });

  it('handles a long invoice with many line items', () => {
    const items = Array.from({ length: 60 }, (_, i) => ({
      id: `item-${i}`,
      sequence_number: i + 1,
      description: `Treatment line item ${i + 1}`,
      quantity: 1,
      unit_price: '100.00',
      discount_type: null,
      discount_value: null,
      net_amount: '100.00',
      tax_amount: null,
      currency_code: 'INR',
    }));

    render(
      <InvoiceDocument
        invoice={makeInvoice({
          items,
          financials: {
            currency_code: 'INR',
            subtotal: '6000.00',
            discount_total: '0.00',
            tax_total: '0.00',
            grand_total: '6000.00',
            paid_amount: '0.00',
            outstanding_amount: '6000.00',
          },
        })}
      />,
    );

    expect(screen.getByText('Treatment line item 1')).toBeInTheDocument();
    expect(screen.getByText('Treatment line item 60')).toBeInTheDocument();
    expect(screen.getAllByText('₹100.00').length).toBe(120); // unit + net per row
    // Subtotal, grand total and balance due all render ₹6,000.00 (nothing paid).
    expect(screen.getAllByText('₹6,000.00').length).toBe(3);
  });

  it('renders gracefully when doctor and notes are absent', () => {
    render(
      <InvoiceDocument
        invoice={makeInvoice({ doctor: null, notes: null })}
      />,
    );

    expect(screen.getByText('Marcus Delaney')).toBeInTheDocument();
    expect(screen.queryByText('Attending doctor')).not.toBeInTheDocument();
    expect(screen.queryByText('Notes')).not.toBeInTheDocument();
  });
});
