import type { FC } from 'react';
import { INVOICE_STATUS_LABELS, PAYMENT_CURRENCY_CODE } from '../../../constants/billing';
import { formatCurrency } from '../../../utils/formatting';
import { formatISODate } from '../../../utils/date';
import type { InvoiceRead } from '../../../types/billing';

/**
 * Presentation currency for the printable document.
 *
 * DensCare's product requirement is INR; the Billing module deliberately
 * presents every amount through `PAYMENT_CURRENCY_CODE` (the documented
 * single point of change), exactly like the sibling `InvoiceLineItemsTable`
 * and `InvoiceFinancialSummaryCard`. The document follows the same rule so
 * a printed invoice always matches what the clinic sees on screen. The
 * monetary VALUES remain the backend's (the invoice's own currency); only
 * the presentation symbol follows the module standard.
 */
const DOCUMENT_CURRENCY_CODE = PAYMENT_CURRENCY_CODE;

interface InvoiceDocumentProps {
  invoice: InvoiceRead;
}

/**
 * InvoiceDocument — professional A4 printable invoice (Task 4).
 *
 * Pure presentational component fed by the already-loaded invoice aggregate
 * (GET /billing/invoices/{id}) — every value is backend-provided, never
 * recomputed. Financial values include the read-time `paid_amount` /
 * `outstanding_amount` that the backend's FinancialCalculationService now
 * attaches correctly.
 *
 * Data principles:
 * - Only backend-supported fields are rendered (no invented branding:
 *   the header uses the system name "DensCare" only — clinic address /
 *   phone / logo are not configured anywhere in the product).
 * - Patient data follows minimum-necessary-data: name + patient code only.
 * - No application metadata leaks into the document: no "generated by"
 *   stamp, no app tagline, no internal staff/audit identifiers (the
 *   doctor's name is shown; the internal doctor code is not).
 * - Currency presents in INR (₹) via `PAYMENT_CURRENCY_CODE` — the module's
 *   approved presentation currency, matching every other Billing surface.
 *
 * The same element is rendered by PrintDocumentDialog for the on-screen
 * preview and the print surface, so preview and print are identical.
 */
export const InvoiceDocument: FC<InvoiceDocumentProps> = ({ invoice }) => {
  const financials = invoice.financials;
  const currencyCode = DOCUMENT_CURRENCY_CODE;
  const hasDoctor = invoice.doctor != null;
  const showTax = Number(financials.tax_total) !== 0;

  return (
    <div className="bg-white p-6 text-neutral-900" data-testid="invoice-document">
      {/* ── Header ─────────────────────────────────────────────── */}
      <div className="flex items-start justify-between gap-4 border-b-2 border-neutral-800 pb-4">
        <div>
          <p className="text-h3 font-bold uppercase tracking-wide text-neutral-900">DensCare</p>
        </div>
        <div className="text-right">
          <p className="text-h2 font-bold uppercase tracking-[0.2em] text-neutral-900">
            Invoice
          </p>
        </div>
      </div>

      {/* ── Metadata ───────────────────────────────────────────── */}
      <dl className="mt-4 grid grid-cols-2 gap-x-6 gap-y-2 text-body-sm">
        <div className="flex justify-between gap-3 border-b border-neutral-100 pb-1.5">
          <dt className="text-neutral-500">Invoice number</dt>
          <dd className="font-semibold tabular-nums">{invoice.invoice_number}</dd>
        </div>
        <div className="flex justify-between gap-3 border-b border-neutral-100 pb-1.5">
          <dt className="text-neutral-500">Invoice date</dt>
          <dd className="tabular-nums">{formatISODate(invoice.invoice_date)}</dd>
        </div>
        <div className="flex justify-between gap-3 border-b border-neutral-100 pb-1.5">
          <dt className="text-neutral-500">Due date</dt>
          <dd className="tabular-nums">{formatISODate(invoice.due_date)}</dd>
        </div>
        <div className="flex justify-between gap-3 border-b border-neutral-100 pb-1.5">
          <dt className="text-neutral-500">Payment status</dt>
          <dd className="font-semibold">{INVOICE_STATUS_LABELS[invoice.status]}</dd>
        </div>
      </dl>

      {/* ── Parties ────────────────────────────────────────────── */}
      <div className="mt-4 grid grid-cols-2 gap-6">
        <div className="print-break-avoid">
          <p className="text-caption font-semibold uppercase tracking-wide text-neutral-500">
            Billed to
          </p>
          <p className="mt-1 text-body font-semibold text-neutral-900">
            {invoice.patient.full_name || '—'}
          </p>
          <p className="text-body-sm text-neutral-500 tabular-nums">
            {invoice.patient.patient_code}
          </p>
        </div>
        {hasDoctor && (
          <div className="print-break-avoid">
            <p className="text-caption font-semibold uppercase tracking-wide text-neutral-500">
              Attending doctor
            </p>
            <p className="mt-1 text-body font-semibold text-neutral-900">
              {invoice.doctor?.user_full_name || '—'}
            </p>
          </div>
        )}
      </div>

      {/* ── Line items ─────────────────────────────────────────── */}
      <table className="mt-5 w-full border-collapse text-left text-body-sm">
        <thead>
          <tr className="border-b-2 border-neutral-300 text-caption font-semibold uppercase tracking-wide text-neutral-500">
            <th scope="col" className="py-2 pr-3">#</th>
            <th scope="col" className="py-2 pr-3">Description</th>
            <th scope="col" className="py-2 pr-3 text-right">Qty</th>
            <th scope="col" className="py-2 pr-3 text-right">Unit price</th>
            <th scope="col" className="py-2 pr-3 text-right">Discount</th>
            <th scope="col" className="py-2 text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          {invoice.items.map((item) => (
            <tr key={item.id} className="border-b border-neutral-100">
              <td className="py-2 pr-3 text-neutral-400 tabular-nums">
                {item.sequence_number}
              </td>
              <td className="py-2 pr-3 font-medium text-neutral-900">
                {item.description}
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">{item.quantity}</td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {formatCurrency(item.unit_price, currencyCode)}
              </td>
              <td className="py-2 pr-3 text-right tabular-nums">
                {item.discount_value != null && item.discount_type
                  ? formatCurrency(item.discount_value, currencyCode)
                  : '—'}
              </td>
              <td className="py-2 text-right font-semibold tabular-nums">
                {formatCurrency(item.net_amount, currencyCode)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* ── Financial summary ──────────────────────────────────── */}
      <div className="print-break-avoid mt-4 flex justify-end">
        <dl className="w-full max-w-xs space-y-1.5 text-body-sm">
          <div className="flex items-center justify-between gap-3">
            <dt className="text-neutral-500">Subtotal</dt>
            <dd className="tabular-nums">{formatCurrency(financials.subtotal, currencyCode)}</dd>
          </div>
          <div className="flex items-center justify-between gap-3">
            <dt className="text-neutral-500">Discount total</dt>
            <dd className="tabular-nums">{formatCurrency(financials.discount_total, currencyCode)}</dd>
          </div>
          {showTax && (
            <div className="flex items-center justify-between gap-3">
              <dt className="text-neutral-500">Tax total</dt>
              <dd className="tabular-nums">{formatCurrency(financials.tax_total, currencyCode)}</dd>
            </div>
          )}
          <div className="flex items-center justify-between gap-3 border-t border-neutral-200 pt-1.5">
            <dt className="font-semibold text-neutral-900">Grand total</dt>
            <dd className="text-body font-bold tabular-nums">
              {formatCurrency(financials.grand_total, currencyCode)}
            </dd>
          </div>
          <div className="flex items-center justify-between gap-3 border-t border-neutral-200 pt-1.5">
            <dt className="text-neutral-500">Amount paid</dt>
            <dd className="font-medium tabular-nums">
              {formatCurrency(financials.paid_amount, currencyCode)}
            </dd>
          </div>
          <div className="flex items-center justify-between gap-3">
            <dt className="font-semibold text-neutral-900">Balance due</dt>
            <dd className="font-semibold tabular-nums">
              {formatCurrency(financials.outstanding_amount, currencyCode)}
            </dd>
          </div>
        </dl>
      </div>

      {/* ── Notes ──────────────────────────────────────────────── */}
      {invoice.notes && (
        <div className="print-break-avoid mt-4 rounded-md bg-neutral-50 p-3">
          <p className="text-caption font-semibold uppercase tracking-wide text-neutral-500">
            Notes
          </p>
          <p className="mt-1 whitespace-pre-wrap break-words text-body-sm text-neutral-700">
            {invoice.notes}
          </p>
        </div>
      )}

    </div>
  );
};
