"""create doctor management tables

Revision ID: 14b364e7b2e5
Revises: 2acc90fbcbf0
Create Date: 2026-07-09 14:56:00.779999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14b364e7b2e5'
down_revision: Union[str, Sequence[str], None] = '2acc90fbcbf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint('code', name='uq_specialization_code'),
    sa.UniqueConstraint('name', name='uq_specialization_name')
    )
    op.create_index('ix_specializations_active', 'specializations', ['is_active'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_code', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('qualification', sa.String(length=500), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('consultation_duration', sa.Integer(), nullable=True),
    sa.Column('languages_known', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True, comment='Array of language strings stored as PostgreSQL JSONB for queryability'),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('available_for_appointment', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('on_leave', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('consultation_duration >= 15 AND consultation_duration <= 240', name='ck_doctors_duration_range'),
    sa.CheckConstraint('consultation_fee > 0', name='ck_doctors_fee_positive'),
    sa.CheckConstraint('years_of_experience >= 0', name='ck_doctors_years_experience'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_code', name='uq_doctor_code'),
    sa.UniqueConstraint('registration_number', name='uq_registration_number'),
    sa.UniqueConstraint('user_id', name='uq_user_id')
    )
    op.create_index('ix_doctors_active_available', 'doctors', ['is_active', 'available_for_appointment'], unique=False)
    op.create_index('ix_doctors_created_by', 'doctors', ['created_by'], unique=False)
    op.create_index('ix_doctors_updated_by', 'doctors', ['updated_by'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Work day start time (e.g. 09:00)'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='Work day end time (e.g. 17:00)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 5', name='ck_schedule_day_of_week'),
    sa.CheckConstraint('end_time > start_time', name='ck_schedule_end_after_start'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedule_active', 'doctor_schedules', ['doctor_id', 'is_active'], unique=False)
    op.create_index('ix_schedule_doctor_day', 'doctor_schedules', ['doctor_id', 'day_of_week'], unique=False)
    op.create_table('doctor_specializations',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('certification_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('doctor_id', 'specialization_id')
    )
    op.create_index('ix_ds_doctor_specialization', 'doctor_specializations', ['doctor_id', 'specialization_id'], unique=False)
    op.create_index('ix_ds_specialization', 'doctor_specializations', ['specialization_id'], unique=False)
    op.create_index('uq_doctor_primary_specialization', 'doctor_specializations', ['doctor_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    
    
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_doctor_primary_specialization', table_name='doctor_specializations', postgresql_where=sa.text('is_primary = true'))
    op.drop_index('ix_ds_specialization', table_name='doctor_specializations')
    op.drop_index('ix_ds_doctor_specialization', table_name='doctor_specializations')
    op.drop_table('doctor_specializations')
    op.drop_index('ix_schedule_doctor_day', table_name='doctor_schedules')
    op.drop_index('ix_schedule_active', table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index('ix_doctors_updated_by', table_name='doctors')
    op.drop_index('ix_doctors_created_by', table_name='doctors')
    op.drop_index('ix_doctors_active_available', table_name='doctors')
    op.drop_table('doctors')
    op.drop_index('ix_specializations_active', table_name='specializations')
    op.drop_table('specializations')
    # ### end Alembic commands ###
