"""create appointments table

Revision ID: 239e5e25d211
Revises: 3733f4eaa564
Create Date: 2026-06-23 18:36:57.441651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239e5e25d211'
down_revision: Union[str, Sequence[str], None] = '3733f4eaa564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_number', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('dentist_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('appointment_type', sa.Enum('Consultation', 'Follow-Up', 'Emergency', 'Procedure', 'Review', 'Other', name='appointment_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('Scheduled', 'Confirmed', 'Checked In', 'In Treatment', 'Completed', 'Cancelled', 'No Show', name='appointment_status_enum'), server_default='Scheduled', nullable=False),
    sa.Column('reason_for_visit', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_appointments_duration_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dentist_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_number')
    )
    op.create_index('ix_appointments_date', 'appointments', ['appointment_date'], unique=False)
    op.create_index('ix_appointments_dentist_schedule', 'appointments', ['dentist_id', 'appointment_date', 'start_time'], unique=False)
    op.create_index('ix_appointments_patient_schedule', 'appointments', ['patient_id', 'appointment_date'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index('ix_appointments_patient_schedule', table_name='appointments')
    op.drop_index('ix_appointments_dentist_schedule', table_name='appointments')
    op.drop_index('ix_appointments_date', table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
