"""add treatment module

Revision ID: 3e904edeca5a
Revises: 14b364e7b2e5
Create Date: 2026-07-14 19:20:17.290741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e904edeca5a'
down_revision: Union[str, Sequence[str], None] = '14b364e7b2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_cost', sa.Numeric(precision=10, scale=2), nullable=False, server_default=sa.text('0.00')),
    sa.Column('category', sa.Enum('diagnostic', 'preventive', 'restorative', 'endodontic', 'periodontic', 'prosthodontic', 'oral_surgery', 'orthodontic', 'cosmetic', 'implant', 'other', name='procedurecategory', native_enum=False, length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.CheckConstraint("category IN ('implant', 'endodontic', 'prosthodontic', 'orthodontic', 'periodontic', 'cosmetic', 'diagnostic', 'other', 'restorative', 'oral_surgery', 'preventive')", name='ck_proc_category'),
    sa.CheckConstraint('default_cost >= 0', name='ck_proc_default_cost'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_procedures_active', 'procedures', ['is_active'], unique=False)
    op.create_index('ix_procedures_category', 'procedures', ['category'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_code', sa.String(length=20), nullable=False),
    sa.Column('patient_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('doctor_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('dentist_recommendations', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'under_review', 'proposed', 'rejected', 'accepted', 'in_progress', 'on_hold', 'completed', 'cancelled', name='treatmentplanstatus', native_enum=False, length=20), nullable=False, server_default=sa.text("'draft'")),
    sa.Column('current_version', sa.Integer(), nullable=False, server_default=sa.text('1')),
    sa.Column('lock_version', sa.Integer(), nullable=False, server_default=sa.text('1')),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('rejected', 'draft', 'proposed', 'accepted', 'under_review', 'cancelled', 'in_progress', 'on_hold', 'completed')", name='ck_tp_status'),
    sa.CheckConstraint('valid_from IS NULL OR valid_to IS NULL OR valid_from <= valid_to', name='ck_tp_valid_dates'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_code')
    )
    op.create_index('ix_tp_active_status', 'treatment_plans', ['is_active', 'status'], unique=False)
    op.create_index('ix_tp_created_at', 'treatment_plans', ['created_at'], unique=False)
    op.create_index('ix_tp_doctor', 'treatment_plans', ['doctor_id'], unique=False)
    op.create_index('ix_tp_patient', 'treatment_plans', ['patient_id'], unique=False)
    op.create_index('ix_tp_status', 'treatment_plans', ['status'], unique=False)
    op.create_table('treatment_plan_approvals',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_status', sa.Enum('pending', 'accepted', 'rejected', 'changes_requested', name='patientacknowledgmentstatus', native_enum=False, length=20), nullable=False, server_default=sa.text("'pending'")),
    sa.Column('patient_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_notes', sa.String(length=500), nullable=True),
    sa.CheckConstraint("patient_status IN ('changes_requested', 'rejected', 'accepted', 'pending')", name='ck_tpa_patient_status'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('treatment_plan_versions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('items_snapshot', postgresql.JSONB(), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version_number >= 1', name='ck_tpv_version_number'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'version_number', name='uq_tp_version_number')
    )
    op.create_table('treatment_plan_items',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('tooth_number', sa.Integer(), nullable=True),
    sa.Column('tooth_surface', sa.String(length=10), nullable=True),
    sa.Column('quadrant', sa.String(length=5), nullable=True),
    sa.Column('arch', sa.String(length=10), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=False, server_default=sa.text('0.00')),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False, server_default=sa.text('0.00')),
    sa.Column('item_status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', 'deferred', name='treatmentplanitemstatus', native_enum=False, length=20), nullable=False, server_default=sa.text("'pending'")),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('appointment_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('diagnosis_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.CheckConstraint("item_status IN ('pending', 'cancelled', 'completed', 'in_progress', 'deferred')", name='ck_tpi_item_status'),
    sa.CheckConstraint('discount <= estimated_cost', name='ck_tpi_discount_le_cost'),
    sa.CheckConstraint('discount >= 0', name='ck_tpi_discount'),
    sa.CheckConstraint('estimated_cost >= 0', name='ck_tpi_estimated_cost'),
    sa.CheckConstraint('tooth_number IS NULL OR (tooth_number BETWEEN 11 AND 48) OR (tooth_number BETWEEN 51 AND 85)', name='ck_tpi_tooth_number'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['patient_record_diagnoses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['treatment_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'sequence_number', name='uq_tp_item_sequence')
    )
    op.create_index('ix_tpi_appointment', 'treatment_plan_items', ['appointment_id'], unique=False)
    op.create_index('ix_tpi_plan', 'treatment_plan_items', ['plan_id'], unique=False)
    op.create_index('ix_tpi_plan_sequence', 'treatment_plan_items', ['plan_id', 'sequence_number'], unique=False)
    op.create_index('ix_tpi_procedure', 'treatment_plan_items', ['procedure_id'], unique=False)
    op.create_index('ix_tpi_status', 'treatment_plan_items', ['plan_id', 'item_status'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###    
    op.drop_index('ix_tpi_procedure', table_name='treatment_plan_items')
    op.drop_index('ix_tpi_plan_sequence', table_name='treatment_plan_items')
    op.drop_index('ix_tpi_plan', table_name='treatment_plan_items')
    op.drop_index('ix_tpi_appointment', table_name='treatment_plan_items')
    op.drop_index('ix_tpi_status', table_name='treatment_plan_items')
    op.drop_table('treatment_plan_items')
    op.drop_table('treatment_plan_versions')
    op.drop_table('treatment_plan_approvals')
    op.drop_index('ix_tp_status', table_name='treatment_plans')
    op.drop_index('ix_tp_patient', table_name='treatment_plans')
    op.drop_index('ix_tp_doctor', table_name='treatment_plans')
    op.drop_index('ix_tp_created_at', table_name='treatment_plans')
    op.drop_index('ix_tp_active_status', table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index('ix_procedures_category', table_name='procedures')
    op.drop_index('ix_procedures_active', table_name='procedures')
    op.drop_table('procedures')
    # ### end Alembic commands ###
