"""sync existing schema with models

Revision ID: b8d407be5e45
Revises: c0594e64fa77
Create Date: 2026-07-01 15:09:45.974885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d407be5e45'
down_revision: Union[str, Sequence[str], None] = 'c0594e64fa77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_patient_code'), table_name='patients')
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    op.create_index('ix_patients_created_at', 'patients', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_users_active_status', 'users', ['is_active', 'status'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_role_id_roles', 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_role_id_roles', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_active_status', table_name='users')
    op.drop_index('ix_patients_created_at', table_name='patients')
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_patient_code'), 'patients', ['patient_code'], unique=False)
    # ### end Alembic commands ###
