from .audit_events import (
    # Patient Record
    PATIENT_RECORD_CREATED,
    PATIENT_RECORD_UPDATED,
    PATIENT_RECORD_STATUS_CHANGED,
    PATIENT_RECORD_FINALIZED,
    PATIENT_RECORD_DELETED,
    # Diagnosis
    DIAGNOSIS_CREATED,
    DIAGNOSIS_BULK_CREATED,
    DIAGNOSIS_UPDATED,
    DIAGNOSIS_DELETED,
    # Prescription
    PRESCRIPTION_CREATED,
    PRESCRIPTION_UPDATED,
    PRESCRIPTION_FINALIZED,
    PRESCRIPTION_DELETED,
    # Prescription Item
    PRESCRIPTION_ITEM_CREATED,
    PRESCRIPTION_ITEM_BULK_CREATED,
    PRESCRIPTION_ITEM_UPDATED,
    PRESCRIPTION_ITEM_DELETED,
    # Attachment
    ATTACHMENT_UPLOADED,
    ATTACHMENT_BULK_UPLOADED,
    ATTACHMENT_UPDATED,
    ATTACHMENT_DELETED,
    # Follow-up
    FOLLOWUP_CREATED,
    FOLLOWUP_UPDATED,
    FOLLOWUP_DELETED,
    # Workflow
    WORKFLOW_RECORD_CREATED,
    WORKFLOW_RECORD_UPDATED,
    WORKFLOW_STATUS_TRANSITIONED,
    WORKFLOW_RECORD_COMPLETED,
    WORKFLOW_RECORD_FINALIZED,
    WORKFLOW_RECORD_ROLLED_BACK,
)

__all__ = [
    # Patient Record
    "PATIENT_RECORD_CREATED",
    "PATIENT_RECORD_UPDATED",
    "PATIENT_RECORD_STATUS_CHANGED",
    "PATIENT_RECORD_FINALIZED",
    "PATIENT_RECORD_DELETED",
    # Diagnosis
    "DIAGNOSIS_CREATED",
    "DIAGNOSIS_BULK_CREATED",
    "DIAGNOSIS_UPDATED",
    "DIAGNOSIS_DELETED",
    # Prescription
    "PRESCRIPTION_CREATED",
    "PRESCRIPTION_UPDATED",
    "PRESCRIPTION_FINALIZED",
    "PRESCRIPTION_DELETED",
    # Prescription Item
    "PRESCRIPTION_ITEM_CREATED",
    "PRESCRIPTION_ITEM_BULK_CREATED",
    "PRESCRIPTION_ITEM_UPDATED",
    "PRESCRIPTION_ITEM_DELETED",
    # Attachment
    "ATTACHMENT_UPLOADED",
    "ATTACHMENT_BULK_UPLOADED",
    "ATTACHMENT_UPDATED",
    "ATTACHMENT_DELETED",
    # Follow-up
    "FOLLOWUP_CREATED",
    "FOLLOWUP_UPDATED",
    "FOLLOWUP_DELETED",
    # Workflow
    "WORKFLOW_RECORD_CREATED",
    "WORKFLOW_RECORD_UPDATED",
    "WORKFLOW_STATUS_TRANSITIONED",
    "WORKFLOW_RECORD_COMPLETED",
    "WORKFLOW_RECORD_FINALIZED",
    "WORKFLOW_RECORD_ROLLED_BACK",
]
